-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 15:48:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema semestral
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema semestral
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `semestral` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `semestral` ;

-- -----------------------------------------------------
-- Table `semestral`.`uzivatele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semestral`.`uzivatele` (
  `iduzivatele` INT(11) NOT NULL AUTO_INCREMENT,
  `jmeno` VARCHAR(60) NULL,
  `heslo` VARCHAR(60) NULL,
  `email` VARCHAR(60) NULL,
  PRIMARY KEY (`iduzivatele`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semestral`.`clanky`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semestral`.`clanky` (
  `idclanky` INT(11) NOT NULL AUTO_INCREMENT,
  `datumcas_vlozeni` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `text` TEXT NULL,
  `titulek` VARCHAR(70) NULL,
  `obrazek` VARCHAR(45) NULL,
  `schvaleno` TINYINT(1) NOT NULL DEFAULT 0,
  `iduzivatele` INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idclanky`),
  INDEX `iduzivatele` (`iduzivatele` ASC),
  CONSTRAINT `iduzivatele`
    FOREIGN KEY (`iduzivatele`)
    REFERENCES `semestral`.`uzivatele` (`iduzivatele`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semestral`.`prava`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semestral`.`prava` (
  `idprava` INT(11) NOT NULL AUTO_INCREMENT,
  `pravo` VARCHAR(100) NULL,
  PRIMARY KEY (`idprava`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semestral`.`prava_to_uzivatele`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semestral`.`prava_to_uzivatele` (
  `idprava` INT(11) NOT NULL,
  `iduzivatele` INT(11) NOT NULL,
  PRIMARY KEY (`idprava`, `iduzivatele`),
  INDEX `iduzivatele` (`iduzivatele` ASC),
  INDEX `idprava` (`idprava` ASC),
  CONSTRAINT `fk_prava_has_uzivatele_prava`
    FOREIGN KEY (`idprava`)
    REFERENCES `semestral`.`prava` (`idprava`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prava_has_uzivatele_uzivatele1`
    FOREIGN KEY (`iduzivatele`)
    REFERENCES `semestral`.`uzivatele` (`iduzivatele`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semestral`.`hodnoceni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semestral`.`hodnoceni` (
  `idhodnoceni` INT(11) NOT NULL AUTO_INCREMENT,
  `iduzivatele` INT(11) NOT NULL,
  `idclanky` INT(11) NOT NULL,
  `pocet_hvezd` INT(11) NOT NULL DEFAULT 0,
  `datumcas_vlozeni` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `hodnoceno` TINYINT(1) NOT NULL DEFAULT 0,
  `iduzivatele_predal` INT(11) NOT NULL,
  `komentar` TEXT NULL,
  PRIMARY KEY (`idhodnoceni`),
  INDEX `iduzivatele` (`iduzivatele` ASC),
  INDEX `idclanky` (`idclanky` ASC),
  INDEX `iduzivatele_predal` (`iduzivatele_predal` ASC),
  CONSTRAINT `fk_hodnoceni_uzivatele1`
    FOREIGN KEY (`iduzivatele`)
    REFERENCES `semestral`.`uzivatele` (`iduzivatele`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hodnoceni_clanky1`
    FOREIGN KEY (`idclanky`)
    REFERENCES `semestral`.`clanky` (`idclanky`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hodnoceni_uzivatele2`
    FOREIGN KEY (`iduzivatele_predal`)
    REFERENCES `semestral`.`uzivatele` (`iduzivatele`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
